export default function Industries() {
  return (
    <>
      <section className="section" id="industries">
        <div className="container">
          <div className="section-head rv">
            <span className="eyebrow">Who We Help</span>
            <h2 className="h2">Deep expertise across the digital economy.</h2>
          </div>
          <div className="ind rv">
            <div className="ind-tabs" role="tablist" aria-label="Industries">
              <button className="ind-tab" role="tab" aria-selected="true" aria-controls="ind-0" id="tab-0">E-Commerce &amp; D2C <span className="arr">→</span></button>
              <button className="ind-tab" role="tab" aria-selected="false" aria-controls="ind-1" id="tab-1">SaaS &amp; Tech <span className="arr">→</span></button>
              <button className="ind-tab" role="tab" aria-selected="false" aria-controls="ind-2" id="tab-2">Professional Services <span className="arr">→</span></button>
              <button className="ind-tab" role="tab" aria-selected="false" aria-controls="ind-3" id="tab-3">Healthcare <span className="arr">→</span></button>
              <button className="ind-tab" role="tab" aria-selected="false" aria-controls="ind-4" id="tab-4">Education <span className="arr">→</span></button>
            </div>
            <div className="ind-panels">
              <div className="ind-panel" role="tabpanel" id="ind-0" aria-labelledby="tab-0">
                <p className="promise">Boosting <span className="accent">average order value</span> and customer lifetime value.</p>
                <p className="proof"><span className="ph">[Case proof — e.g., lift in repeat purchase rate after rebuilding post-purchase flows]</span></p>
                <div className="ind-tags"><span>Store &amp; funnel builds</span><span>CRO</span><span>Retention flows</span><span>High-intent SEO</span></div>
              </div>
              <div className="ind-panel" role="tabpanel" id="ind-1" aria-labelledby="tab-1" hidden={true}>
                <p className="promise">Accelerating <span className="accent">user activation</span> and reducing churn.</p>
                <p className="proof"><span className="ph">[Case proof — e.g., trial-to-paid conversion lift from personalized onboarding]</span></p>
                <div className="ind-tags"><span>Marketing sites</span><span>Onboarding journeys</span><span>Product dashboards</span><span>Content authority</span></div>
              </div>
              <div className="ind-panel" role="tabpanel" id="ind-2" aria-labelledby="tab-2" hidden={true}>
                <p className="promise">Earning <span className="accent">authority</span> and nurturing long-term client relationships.</p>
                <p className="proof"><span className="ph">[Case proof — e.g., MQLs generated by a thought-leadership program in its first quarter]</span></p>
                <div className="ind-tags"><span>Thought leadership</span><span>Lead capture</span><span>Local SEO</span><span>GEO / AI answers</span></div>
              </div>
              <div className="ind-panel" role="tabpanel" id="ind-3" aria-labelledby="tab-3" hidden={true}>
                <p className="promise">Guiding patients to <span className="accent">the right care</span> with compassion and precision.</p>
                <p className="proof"><span className="ph">[Case proof — e.g., increase in appointment requests after a patient-journey rebuild]</span></p>
                <div className="ind-tags"><span>Clinic landing pages</span><span>Local SEO</span><span>Appointment funnels</span><span>Trust content</span></div>
              </div>
              <div className="ind-panel" role="tabpanel" id="ind-4" aria-labelledby="tab-4" hidden={true}>
                <p className="promise">Designing learning experiences that <span className="accent">engage and inspire.</span></p>
                <p className="proof"><span className="ph">[Case proof — e.g., course completion lift after introducing adaptive learning paths]</span></p>
                <div className="ind-tags"><span>Course platforms &amp; LMS</span><span>Enrollment funnels</span><span>Community</span><span>Search visibility</span></div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
